# **Data**

Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot

Importing the dataset

In [ ]:
dataset = pd.read_csv("news.csv")
y = dataset.iloc[:,-1].values
y

array(['FAKE', 'FAKE', 'REAL', ..., 'FAKE', 'REAL', 'REAL'], dtype=object)

 Unique Data

In [ ]:
#Unique Data in dependent variable
dataset.iloc[:,-1].value_counts()

REAL    3171
FAKE    3164
Name: label, dtype: int64

Dropping Irrelevant columns

In [ ]:
dataset.drop(['Unnamed: 0'],axis= 1, inplace= True)
dataset

title  ... label
0                          You Can Smell Hillary’s Fear  ...  FAKE
1     Watch The Exact Moment Paul Ryan Committed Pol...  ...  FAKE
2           Kerry to go to Paris in gesture of sympathy  ...  REAL
3     Bernie supporters on Twitter erupt in anger ag...  ...  FAKE
4      The Battle of New York: Why This Primary Matters  ...  REAL
...                                                 ...  ...   ...
6330  State Department says it can't find emails fro...  ...  REAL
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  ...  FAKE
6332  Anti-Trump Protesters Are Tools of the Oligarc...  ...  FAKE
6333  In Ethiopia, Obama seeks progress on peace, se...  ...  REAL
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  ...  REAL

[6335 rows x 3 columns]

Analysis of Data types

In [ ]:
# training set
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6335 entries, 0 to 6334
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   6335 non-null   object
 1   text    6335 non-null   object
 2   label   6335 non-null   object
dtypes: object(3)
memory usage: 148.6+ KB


# **Data Preprocessing**

Taking care of missing data

In [ ]:
# checking missing data in each column of training set
dataset.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [ ]:
# Creating a new column with name total
dataset['total'] = dataset['title'] + ' ' + dataset['text']
print(dataset.shape)
dataset


(6335, 4)


title  ...                                              total
0                          You Can Smell Hillary’s Fear  ...  You Can Smell Hillary’s Fear Daniel Greenfield...
1     Watch The Exact Moment Paul Ryan Committed Pol...  ...  Watch The Exact Moment Paul Ryan Committed Pol...
2           Kerry to go to Paris in gesture of sympathy  ...  Kerry to go to Paris in gesture of sympathy U....
3     Bernie supporters on Twitter erupt in anger ag...  ...  Bernie supporters on Twitter erupt in anger ag...
4      The Battle of New York: Why This Primary Matters  ...  The Battle of New York: Why This Primary Matte...
...                                                 ...  ...                                                ...
6330  State Department says it can't find emails fro...  ...  State Department says it can't find emails fro...
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  ...  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...
6332  Anti-Trump Protesters Are Tools of the Oligarc...  ...  Anti-Trump Protesters Are Tools of the Oligarc...
6333  In Ethiopia, Obama seeks progress on peace, se...  ...  In Ethiopia, Obama seeks progress on peace, se...
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  ...  Jeb Bush Is Suddenly Attacking Trump. Here's W...

[6335 rows x 4 columns]

Taking care of categorical variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y


array([0, 0, 1, ..., 0, 1, 1])

Cleaning Text and stemming

In [ ]:
# for training set
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(dataset.shape[0]):
  news = re.sub('[^a-zA-Z]', ' ', dataset.iloc[i,-1])
  news = news.lower()
  news = news.split()
  all_stopwords = stopwords.words('english')
  ps = PorterStemmer()
  lis = []
  for word in news:
    if word not in all_stopwords:
      word = ps.stem(word)
      lis.append(word)
  corpus.append(" ".join(lis))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
corpus[0]

'smell hillari fear daniel greenfield shillman journal fellow freedom center new york writer focus radic islam final stretch elect hillari rodham clinton gone war fbi word unpreced thrown around often elect ought retir still unpreced nomine major polit parti go war fbi exactli hillari peopl done coma patient wake watch hour cnn hospit bed would assum fbi director jame comey hillari oppon elect fbi attack everyon obama cnn hillari peopl circul letter attack comey current media hit piec lambast target trump surpris clinton alli start run attack ad fbi fbi leadership warn entir left wing establish form lynch mob continu go hillari fbi credibl attack media democrat preemptiv head result investig clinton foundat hillari clinton covert struggl fbi agent obama doj peopl gone explos public new york time compar comey j edgar hoover bizarr headlin jame comey role recal hoover fbi fairli practic admit front spout nonsens boston globe publish column call comey resign outdon time editori claim scan

# **Tf-IDF Vectorizer**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features= 20000,ngram_range=(1,3))
x = tfidf.fit_transform(corpus).toarray()
x.shape

(6335, 20000)

In [ ]:
count_df = pd.DataFrame(x, columns=tfidf.get_feature_names())
count_df.head(50)

aa  aaron  abaaoud  abadi  ...      zone  zone syria  zuckerberg  zulu
0   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
1   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
2   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
3   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
4   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
5   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
6   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
7   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
8   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
9   0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
10  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
11  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
12  0.083888    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
13  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
14  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
15  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
16  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
17  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
18  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
19  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
20  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
21  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
22  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
23  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
24  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
25  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
26  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
27  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
28  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
29  0.000000    0.0      0.0    0.0  ...  0.027753         0.0         0.0   0.0
30  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
31  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
32  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
33  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
34  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
35  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
36  0.000000    0.0      0.0    0.0  ...  0.048358         0.0         0.0   0.0
37  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
38  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
39  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
40  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
41  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
42  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
43  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
44  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
45  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
46  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
47  0.000000    0.0      0.0    0.0  ...  0.000000         0.0         0.0   0.0
48  0.000000    0.0      0.0    0.0  ... 

# Splitting the training and test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)
x_train.shape

(5068, 20000)

MultinomialNB

In [ ]:
#DataFlair - Initialize a PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

Passive Aggresive Classifier

In [ ]:
from sklearn.linear_model import PassiveAggressiveClassifier
pac = PassiveAggressiveClassifier(max_iter=50)
pac.fit(x_train, y_train)

PassiveAggressiveClassifier(C=1.0, average=False, class_weight=None,
                            early_stopping=False, fit_intercept=True,
                            loss='hinge', max_iter=50, n_iter_no_change=5,
                            n_jobs=None, random_state=None, shuffle=True,
                            tol=0.001, validation_fraction=0.1, verbose=0,
                            warm_start=False)

Predicting the result

In [ ]:
# predicting result for multinomialNB
y_pred_m = classifier.predict(x_test)
y_pred_m

array([1, 1, 0, ..., 1, 1, 0])

In [ ]:
# predicting result for passiveagressive
y_pred_p = pac.predict(x_test)
y_pred_p

array([1, 0, 0, ..., 0, 1, 0])

Confusion Matrix and Accuracy Score

In [ ]:
# for multinomialnb
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_m)
print(cm)
accuracy_score(y_test, y_pred_m)

[[540  75]
 [ 62 590]]


0.8918705603788477

In [ ]:
# for passive agressive Classifier
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_p)
print(cm)
accuracy_score(y_test, y_pred_p)

[[573  42]
 [ 40 612]]


0.9352801894238358